# Generated by Django 5.0.3 on 2024-04-11 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conf', models.TextField()),
                ('dag_id', models.CharField(max_length=255)),
                ('dag_run_id', models.CharField(max_length=255)),
                ('data_interval_start', models.DateTimeField(auto_now_add=True)),
                ('data_interval_end', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('external_trigger', models.BooleanField()),
                ('last_scheduling_decision', models.CharField(max_length=255, null=True)),
                ('logical_date', models.DateTimeField(auto_now_add=True)),
                ('run_type', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mysql_connector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(default='mysql')),
                ('username', models.CharField(max_length=100)),
                ('database', models.CharField(max_length=100)),
                ('host', models.GenericIPAddressField()),
                ('password', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Matrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(max_length=100)),
                ('num_rows', models.IntegerField()),
                ('num_columns', models.IntegerField()),
                ('num_duplicate_rows', models.IntegerField()),
                ('null_values_per_column', models.JSONField(max_length=1000)),
                ('std_per_column_dict', models.JSONField(max_length=1000)),
                ('status', models.CharField(max_length=100)),
                ('ingestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connectors.ingestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connectors.mysql_connector')),
            ],
        ),
    ]
