# Generated by Django 5.0.3 on 2024-04-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestion',
            name='box_plot_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mysql_connector',
            name='service_name',
            field=models.CharField(default='mysql', max_length=100),
        ),
    ]
