# Generated by Django 5.0.3 on 2024-04-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0002_ingestion_box_plot_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_name', models.CharField(max_length=100)),
                ('warehouse_image', models.ImageField(blank=True, null=True, upload_to='data_warehouser')),
            ],
        ),
    ]
