# Generated by Django 5.0.3 on 2024-04-22 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0003_data_warehouse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data_Warehouse',
        ),
    ]
